package humanizelint //nolint:testpackage // white-box: tests IsGeneratedFile detector

import (
	"path/filepath"
	"testing"
)

// TestIsGeneratedFile_FilenameOnly verifies the filename-only detection path
// (content == nil). This is the path the golangci-lint plugin takes because
// pass.Files doesn't carry file content. The original inline check caught
// only _gen.go, .gen.go, _templ.go — these cases must remain green so we
// don't regress existing tooling.
//
// New generators brought in by gogenfilter should also pass. If a generator is
// dropped from gogenfilter, this test will fail loud and force us to decide
// whether to keep coverage.
func TestIsGeneratedFile_FilenameOnly(t *testing.T) {
	t.Parallel()

	cases := []struct {
		path string
		want bool
	}{
		// Regression — original three patterns must keep working.
		{"foo_gen.go", true},
		{"foo.gen.go", true},
		{"foo_templ.go", true},
		{"nested/dir/foo_gen.go", true},

		// Negative — hand-written code must not be flagged.
		{"foo.go", false},
		{"foo_test.go", false},
		{"main.go", false},
		{"nested/dir/main.go", false},

		// New generators brought in by gogenfilter — these previously
		// slipped through and would have been linted as hand-written code.
		//
		// sqlc: gogenfilter v3.5.0 (2026-08-10) made the bare sqlc default
		// names (models.go, querier.go, batch.go, db.go, copyfrom.go)
		// config-aware: they are classified as generated only when a
		// reachable sqlc.yaml declares their parent directory as an output
		// dir, or via the "Code generated by sqlc" content marker. The
		// filename-only DetectReason path therefore returns false for them —
		// a deliberate upstream false-positive fix (hand-written batch.go in
		// non-sqlc repos caused ~12 FPs in the 2026-08-10 sweep). The
		// per-query `.sql.go` suffix convention is still filename-detected.
		{"models.go", false},               // sqlc default name: needs content/config
		{"querier.go", false},              // sqlc default name: needs content/config
		{"batch.go", false},                // sqlc default name: needs content/config
		{"query.sql.go", true},             // sqlc per-query convention
		{"user.pb.go", true},               // protobuf
		{"user_grpc.pb.go", true},          // protobuf
		{"zz_generated.deepcopy.go", true}, // deepcopy-gen (zz_generated.*.go)
		{"wire_gen.go", true},              // wire
		{"service_moq.go", true},           // moq
		{"service_moq_test.go", true},      // moq
		{"service_mock.go", true},          // mockgen
		{"mock_service.go", true},          // mockery
		{"models_easyjson.go", true},       // easyjson
		{"fake_service.go", true},          // counterfeiter
		{"color_kind.go", false},           // not a known generator pattern
	}

	for _, tt := range cases {
		// Use an absolute path so gogenfilter's filepath.Base(line 564) and
		// matchesSQLCFilenamePattern (which checks filepath.Base) agree.
		absPath := filepath.Join("/repo", tt.path)

		got := IsGeneratedFile(absPath, nil)
		if got != tt.want {
			t.Errorf("IsGeneratedFile(%q, nil) = %v, want %v", tt.path, got, tt.want)
		}
	}
}

// TestIsGeneratedFile_ContentPhase verifies that providing content enables
// detectors that cannot be guessed from the filename alone. The walker uses
// this path because it reads the file once for parsing.
//
// We use _enum.go for go-enum because gogenfilter's go-enum detector requires
// both the filename suffix AND the "// Code generated by go-enum" content
// marker. The same comment convention triggers the generic fallback, so any
// file with the marker is detected regardless of filename.
func TestIsGeneratedFile_ContentPhase(t *testing.T) {
	t.Parallel()

	const genericMarker = "// Code generated by some-tool; DO NOT EDIT.\n"

	cases := []struct {
		name    string
		path    string
		content string
		want    bool
	}{
		{
			name:    "generic Code generated by marker",
			path:    "/repo/handler.go",
			content: genericMarker + "package main\n",
			want:    true,
		},
		{
			name:    "go-enum filename + content",
			path:    "/repo/color_enum.go",
			content: "// Code generated by go-enum; DO NOT EDIT.\npackage main\n",
			want:    true,
		},
		{
			name:    "stringer content-only (no filename hint)",
			path:    "/repo/ipsum.go",
			content: "// Code generated by \"stringer\"; DO NOT EDIT.\npackage main\n",
			want:    true,
		},
		{
			name:    "sqlc default name + sqlc content marker",
			path:    "/repo/db/models.go",
			content: "// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
			want:    true,
		},
		{
			name:    "hand-written content stays clean",
			path:    "/repo/handler.go",
			content: "package main\n\nfunc main() {}\n",
			want:    false,
		},
		{
			name:    "empty content is filename-only",
			path:    "/repo/handler.go",
			content: "",
			want:    false,
		},
	}

	for _, tt := range cases {
		got := IsGeneratedFile(tt.path, []byte(tt.content))
		if got != tt.want {
			t.Errorf("%s: IsGeneratedFile(%q, %q) = %v, want %v",
				tt.name, tt.path, tt.content, got, tt.want)
		}
	}
}

// TestIsGeneratedFile_RegressionOriginalThree hard-codes the exact three
// patterns the previous inline isGenerated caught. If any of these regress,
// something is dropping coverage that real-world code depends on.
func TestIsGeneratedFile_RegressionOriginalThree(t *testing.T) {
	t.Parallel()

	for _, p := range []string{"foo_gen.go", "foo.gen.go", "foo_templ.go"} {
		if !IsGeneratedFile(p, nil) {
			t.Errorf("regression: IsGeneratedFile(%q, nil) returned false, expected true", p)
		}
	}
}
