package humanizelint

import (
	"github.com/LarsArtmann/gogenfilter/v3"
)

// IsGeneratedFile reports whether a file looks like auto-generated Go code.
// The check covers every generator supported by
// github.com/LarsArtmann/gogenfilter/v3 (sqlc, templ, protobuf, deepcopy-gen,
// wire, moq, mockgen, mockery, easyjson, counterfeiter, etc.) plus the generic
// "// Code generated by" fallback per https://go.dev/s/generatedcode.
//
// Two-phase detection is delegated to gogenfilter:
//
//  1. Filename-only phase (zero I/O) — runs whenever path is non-empty.
//  2. Content phase — runs only when content is non-empty. Pass nil to skip
//     the content phase (e.g. from the golangci-lint plugin runtime, where
//     the file content is already held by the analyzer and reading again
//     would be wasteful).
//
// Callers that already read the file (the walker) should pass the content;
// callers that have only the path (the plugin) should pass nil.
func IsGeneratedFile(path string, content []byte) bool {
	reason := gogenfilter.DetectReason(path, string(content), gogenfilter.FilterAll)

	return reason != gogenfilter.ReasonNotFiltered
}
