package humanizelint

import (
	"strings"

	"github.com/LarsArtmann/gogenfilter/v3"
)

// IsGeneratedFile reports whether a file looks like auto-generated Go code.
// The check covers every generator supported by
// github.com/LarsArtmann/gogenfilter/v3 (sqlc, templ, protobuf, deepcopy-gen,
// wire, moq, mockgen, mockery, easyjson, counterfeiter, etc.) plus the generic
// "// Code generated by" fallback per https://go.dev/s/generatedcode.
//
// Two-phase detection is delegated to gogenfilter:
//
//  1. Filename-only phase (zero I/O) — runs whenever path is non-empty.
//  2. Content phase — runs only when content is non-empty. Pass nil to skip
//     the content phase (e.g. from the golangci-lint plugin runtime, where
//     the file content is already held by the analyzer and reading again
//     would be wasteful).
//
// Callers that already read the file (the walker) should pass the content;
// callers that have only the path (the plugin) should pass nil.
//
// Compatibility note: gogenfilter does not enumerate every tooling convention.
// In particular, the generic `_gen.go` and `.gen.go` suffixes (used by
// go-enum-output, deep-copy generators, hand-rolled `go generate` outputs,
// etc.) are NOT detected by gogenfilter's table (it only knows specific
// patterns like `wire_gen.go`). To preserve the original behaviour of the
// inline checks this helper replaced, we run a small fallback that catches
// those three conventions when gogenfilter reports nothing.
func IsGeneratedFile(path string, content []byte) bool {
	reason := gogenfilter.DetectReason(path, string(content), gogenfilter.FilterAll)
	if reason != gogenfilter.ReasonNotFiltered {
		return true
	}

	return matchesLegacyGeneratedSuffix(path)
}

// matchesLegacyGeneratedSuffix reports whether the file basename ends with
// one of the three legacy generated-file suffixes (_gen.go, .gen.go,
// _templ.go) that the original inline isGenerated checked. Kept so existing
// users of the linter don't get spurious findings on files gogenfilter does
// not know about.
func matchesLegacyGeneratedSuffix(path string) bool {
	base := path
	if idx := strings.LastIndex(path, "/"); idx >= 0 {
		base = path[idx+1:]
	}

	return strings.HasSuffix(base, "_gen.go") ||
		strings.HasSuffix(base, ".gen.go") ||
		strings.HasSuffix(base, "_templ.go")
}
